# Publish to TestPyPI
#
# This workflow publishes nii2dcm on TestPyPI prior to production release onto PyPI. The workflow is intended to catch
# any issues arising during the release procedure to prevent unnecessary versioning issues on PyPI
#
# This workflow will upload a Python Package using Twine when a release is created. For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish package to TestPyPI

on:
  pull_request

permissions:
  contents: read

jobs:
  testpypi-publish:

    name: Publish release to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/nii2dcm
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for PyPI trusted publishing

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        verbose: true