# Publish to TestPyPI
#
# This workflow publishes nii2dcm on TestPyPI prior to
# production release onto PyPI. The workflow is intended to
# catch any issues arising during the release procedure to
# prevent unnecessary versioning issues on PyPI.
#
# This workflow will upload a Python Package using Twine when a release is created. For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish package to TestPyPI

on:
  push:
    branches:
      - main
      - 24-gha-pypi

permissions:
  contents: read
  actions: write

jobs:
  testpypi-publish:

    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/nii2dcm
    permissions:
      contents: read
      actions: write
      id-token: write  # IMPORTANT: this permission is mandatory for PyPI trusted publishing

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt

    - name: Build package
      run: pip install .

    - name: Display version via dunamai
      run: |
        echo "version via dunamai:"
        dunamai from any

    - name: Display version via nii2dcm CLI
      run: |
        echo "version via nii2dcm CLI:"
        nii2dcm -v

    - name: Create dist/
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Remove .egg
      run: |
        echo "dist/ before:"
        ls dist/
        [ -f "./dist/*.egg" ] && "Deleting .egg file as not permitted on PyPI" || rm ./dist/*.egg
        echo "dist/ after:"
        ls dist/

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true

    - name: Wait to allow TestPyPI to update
      uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '150'  # seconds

    - name: Install latest TestPyPI version in fresh venv
      run: |
        NII2DCM_VERSION=`echo "$(nii2dcm -v)"`
        echo $NII2DCM_VERSION
        python -m venv nii2dcm-temp
        source nii2dcm-temp/bin/activate
        pip install --upgrade pip
        pip install setuptools wheel
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ nii2dcm==$NII2DCM_VERSION
        nii2dcm -h
        echo "nii2dcm version:"
        nii2dcm -v
